#pragma once

/*
 * cortex piece types
 */

#include "types.h"

typedef u8 cortex_piece;
typedef u8 cortex_piece_type;
typedef u8 cortex_piece_color;

/* piece colors */
#define CORTEX_PIECE_COLOR_WHITE 1
#define CORTEX_PIECE_COLOR_BLACK 0

/* piece types */
#define CORTEX_PIECE_TYPE_NONE   0
#define CORTEX_PIECE_TYPE_PAWN   1
#define CORTEX_PIECE_TYPE_KING   2
#define CORTEX_PIECE_TYPE_QUEEN  3
#define CORTEX_PIECE_TYPE_ROOK   4
#define CORTEX_PIECE_TYPE_BISHOP 5
#define CORTEX_PIECE_TYPE_KNIGHT 6

#define CORTEX_PIECE_IS_MINOR(p) ((p & 0xF) >= 4 && (p & 0xF) <= 6)

/* piece color assignment and querying */
#define CORTEX_PIECE_TO_WHITE(p) (p | (1 << 7))
#define CORTEX_PIECE_TO_BLACK(p) (p & ~(1 << 7))
#define CORTEX_PIECE_GET_COLOR(p) (p >> 7)

#define CORTEX_PIECE_GET_TYPE(p) (p & 0xF)
#define CORTEX_PIECE_IS_VALID(p) ((p & 0xF) <= 6)

/* shortcut basic pieces */
#define CORTEX_PIECE_BLACK_PAWN   CORTEX_PIECE_TYPE_PAWN
#define CORTEX_PIECE_BLACK_KING   CORTEX_PIECE_TYPE_KING
#define CORTEX_PIECE_BLACK_QUEEN  CORTEX_PIECE_TYPE_QUEEN
#define CORTEX_PIECE_BLACK_ROOK   CORTEX_PIECE_TYPE_ROOK
#define CORTEX_PIECE_BLACK_BISHOP CORTEX_PIECE_TYPE_BISHOP
#define CORTEX_PIECE_BLACK_KNIGHT CORTEX_PIECE_TYPE_KNIGHT

#define CORTEX_PIECE_WHITE_PAWN   CORTEX_PIECE_TO_WHITE(CORTEX_PIECE_TYPE_PAWN)
#define CORTEX_PIECE_WHITE_KING   CORTEX_PIECE_TO_WHITE(CORTEX_PIECE_TYPE_KING)
#define CORTEX_PIECE_WHITE_QUEEN  CORTEX_PIECE_TO_WHITE(CORTEX_PIECE_TYPE_QUEEN)
#define CORTEX_PIECE_WHITE_ROOK   CORTEX_PIECE_TO_WHITE(CORTEX_PIECE_TYPE_ROOK)
#define CORTEX_PIECE_WHITE_BISHOP CORTEX_PIECE_TO_WHITE(CORTEX_PIECE_TYPE_BISHOP)
#define CORTEX_PIECE_WHITE_KNIGHT CORTEX_PIECE_TO_WHITE(CORTEX_PIECE_TYPE_KNIGHT)

char cortex_piece_type_char(cortex_piece p);
